### ISSUE TITLE
errors for users of node < v4 due to es6 usage

### ISSUE THREAD

**Issue by nickdesaulniers** [MayhemYDG/iltorb#1]
```
➜  brotli  node app.js
/Users/Nicholas/code/js/brotli/node_modules/iltorb/index.js:10
const encode = require('./build/Release/encode.node');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Nicholas/code/js/brotli/app.js:4:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```
where app.js looks like:
```js
var compression = require('compression')
var connect = require('connect')
var http = require('http')
var brotli = require('iltorb')

var app = connect()

// gzip/deflate outgoing responses
var opts = {
  compressor: {
    brotli: brotli.compressStream(),
  },
};
app.use(compression(opts))

// respond to all requests
app.use(function(req, res){
  res.end('Hello from Connect!\n');
})

// create node.js http server and listen on port
http.createServer(app).listen(3000)

```

**Comment by MayhemYDG** [comment]
On what version on Node did you test that?

**Comment by nickdesaulniers** [comment]
0.12.7

**Comment by nickdesaulniers** [comment]
looks like a bunch of errors due to the use of some es6 features

**Comment by MayhemYDG** [comment]
Yes obviously.
Can you afford to make the jump to the LTS (4.2.1 right now)? 0.12.7 is using a really old V8.

**Comment by nickdesaulniers** [comment]
I have no problem, but you'll probably have users continue to run into this issue for a while.  While not transpile to es5 in the meantime?

**Comment by MayhemYDG** [comment]
I thought that most people would have upgraded by now.
I'll try and downgrade this to ES5.

**Comment by nickdesaulniers** [comment]
nice, thank you! Let me know when a new version has been published to npm that I can pull in.

**Comment by MayhemYDG** [comment]
I've just published 1.0.5.
Travis seems fine when testing for node 0.12.
Let me know how it works for you.

**Comment by nickdesaulniers** [comment]
looks great, thank you, I appreciate it!

**Comment by MayhemYDG** [comment]
:ok_hand:
