### ISSUE TITLE
make: *** No rule to make target `Release/obj.target/iltorb/brotli/c/common/dictionary.o', needed by `Release/iltorb.node'.  Stop.

### ISSUE THREAD

**Issue by peichen3141** [MayhemYDG/iltorb#117]
I tried to prebuild iltorb@2.4.5 for node 14.7.0 on darwin-x64 using node-gyp,
and see error:
make: *** No rule to make target `Release/obj.target/iltorb/brotli/c/common/dictionary.o', needed by `Release/iltorb.node'.  Stop.

What I do is download the repo and run npm install. Is there anything wrong? Is there any dependency I should be aware of?

**Comment by peichen3141** [comment]
Full log:
prebuild info begin Prebuild version 10.0.1
prebuild info build Preparing to prebuild iltorb@2.4.5 for node 14.7.0 on darwin-x64 using node-gyp
prebuild info find Python using Python version 3.8.2 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
prebuild info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
prebuild info spawn args [
prebuild info spawn args   '/Users/peichen/.nvm/versions/node/v14.7.0/lib/node_modules/prebuild/node_modules/node-gyp/gyp/gyp_main.py',
prebuild info spawn args   'binding.gyp',
prebuild info spawn args   '-Dmodule_name=iltorb',
prebuild info spawn args   '-Dmodule_path=./build/bindings',
prebuild info spawn args   '-f',
prebuild info spawn args   'make',
prebuild info spawn args   '-I',
prebuild info spawn args   '/Users/peichen/Documents/iltorb/build/config.gypi',
prebuild info spawn args   '-I',
prebuild info spawn args   '/Users/peichen/.nvm/versions/node/v14.7.0/lib/node_modules/prebuild/node_modules/node-gyp/addon.gypi',
prebuild info spawn args   '-I',
prebuild info spawn args   '/var/folders/34/2f1dp1yx5jnb46wv4v7bc7bc0000gq/T/prebuild/node/14.7.0/include/node/common.gypi',
prebuild info spawn args   '-Dlibrary=shared_library',
prebuild info spawn args   '-Dvisibility=default',
prebuild info spawn args   '-Dnode_root_dir=/var/folders/34/2f1dp1yx5jnb46wv4v7bc7bc0000gq/T/prebuild/node/14.7.0',
prebuild info spawn args   '-Dnode_gyp_dir=/Users/peichen/.nvm/versions/node/v14.7.0/lib/node_modules/prebuild/node_modules/node-gyp',
prebuild info spawn args   '-Dnode_lib_file=/var/folders/34/2f1dp1yx5jnb46wv4v7bc7bc0000gq/T/prebuild/node/14.7.0/<(target_arch)/node.lib',
prebuild info spawn args   '-Dmodule_root_dir=/Users/peichen/Documents/iltorb',
prebuild info spawn args   '-Dnode_engine=v8',
prebuild info spawn args   '--depth=.',
prebuild info spawn args   '--no-parallel',
prebuild info spawn args   '--generator-output',
prebuild info spawn args   'build',
prebuild info spawn args   '-Goutput_dir=.'
prebuild info spawn args ]
prebuild info spawn make
prebuild info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: *** No rule to make target `Release/obj.target/iltorb/brotli/c/common/dictionary.o', needed by `Release/iltorb.node'.  Stop.
prebuild ERR! build error
prebuild ERR! stack Error: `make` failed with exit code: 2
prebuild ERR! stack     at ChildProcess.onExit (/Users/peichen/.nvm/versions/node/v14.7.0/lib/node_modules/prebuild/node_modules/node-gyp/lib/build.js:194:23)
prebuild ERR! stack     at ChildProcess.emit (events.js:314:20)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
prebuild ERR! not ok
prebuild ERR! build Error: `make` failed with exit code: 2
prebuild ERR! build     at ChildProcess.onExit (/Users/peichen/.nvm/versions/node/v14.7.0/lib/node_modules/prebuild/node_modules/node-gyp/lib/build.js:194:23)
prebuild ERR! build     at ChildProcess.emit (events.js:314:20)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)

**Comment by nstepien** [comment]
iltorb is deprecated, please use the official API instead:
https://nodejs.org/dist/latest-v14.x/docs/api/zlib.html#zlib_zlib_createbrotlicompress_options
