### ISSUE TITLE
iltorb fails to build on linux (CentOS/Redhat)

### ISSUE THREAD

**Issue by mokingguy** [MayhemYDG/iltorb#14]
Like the title says, one library of the generator-angular-fullstack depends on iltorb, which it fails to install using `npm install` I've gone a little on more detail on an issue [there](https://github.com/angular-fullstack/generator-angular-fullstack/issues/2190) But tl;dr: 

npm says

```
npm ERR! Failed at the iltorb@1.0.12 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iltorb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iltorb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iltorb
npm ERR! There is likely additional logging output above.
```

Someone suggested to build manually iltorb, which i did and spat back this

```
root@server [/home/tararaapp-backend-panel/litorbTest/iltorb]# node-gyp --python /usr/src/Python-2.7.12/python configure            
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.2.0 | linux | x64
gyp info spawn /usr/src/Python-2.7.12/python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/tararaapp-backend-panel/litorbTest/iltorb/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/6.2.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/6.2.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/tararaapp-backend-panel/litorbTest/iltorb',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 

root@server [/home/tararaapp-backend-panel/litorbTest/iltorb]# node-gyp --python /usr/src/Python-2.7.12/python build                
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.2.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/tararaapp-backend-panel/litorbTest/iltorb/build'
make: *** No rule to make target `Release/obj.target/decode/brotli/common/dictionary.o', needed by `Release/obj.target/decode.node'.
  Stop.
make: Leaving directory `/home/tararaapp-backend-panel/litorbTest/iltorb/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 2.6.32-642.1.1.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "--python" "/usr/src/Python-2.7.12/python" "build"
gyp ERR! cwd /home/tararaapp-backend-panel/litorbTest/iltorb
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

I have running:

Dependency | Version
-------------|------------
node|6.2.0
npm|3.10.6
node-gyp|3.4.0
gcc|4.4.7
make|3.8.1
pyhton|2.6 for system use but i've set to explicitly use 2.7.12 i've separately installed

**Comment by MayhemYDG** [comment]
You forgot to fetch the git submodule before building iltorb manually. I suggest cloning with `--recursive`:
```
git clone https://github.com/MayhemYDG/iltorb.git --recursive
```
Try `node-gyp rebuild` again after that, maybe that'll give us more clues.

**Comment by mokingguy** [comment]
Ok I just did and said this:

```
root@server [/home/tararaapp-backend-panel/litorbTest]# rm -rf iltorb/           
                                                   
root@server [/home/tararaapp-backend-panel/litorbTest]# git clone https://github.com/MayhemYDG/iltorb.git --recursive
Cloning into 'iltorb'...
remote: Counting objects: 344, done.                                                                                                
remote: Total 344 (delta 0), reused 0 (delta 0), pack-reused 344                                                                    
Receiving objects: 100% (344/344), 21.78 MiB | 23.77 MiB/s, done.
Resolving deltas: 100% (195/195), done.
Checking connectivity... done.
Submodule 'brotli' (https://github.com/google/brotli) registered for path 'brotli'
Cloning into '/home/tararaapp-backend-panel/litorbTest/iltorb/brotli'...
Submodule path 'brotli': checked out '3116718689c5a0af87b17b07d3b4cefbb57b974e'
Submodule 'terryfy' (https://github.com/MacPython/terryfy.git) registered for path 'brotli/terryfy'
Cloning into '/home/tararaapp-backend-panel/litorbTest/iltorb/brotli/terryfy'...
Submodule path 'brotli/terryfy': checked out '8bb673f4410819df06920fdcfd24e18d235d84f7'

root@server [/home/tararaapp-backend-panel/litorbTest]# cd iltorb/
root@server [/home/tararaapp-backend-panel/litorbTest/iltorb]# ls
./   appveyor.yml  brotli/  .gitignore   index.js  package.json  src/   .travis.yml
../  binding.gyp   .git/    .gitmodules  LICENSE   README.md     test/

root@server [/home/tararaapp-backend-panel/litorbTest/iltorb]# node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.2.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/tararaapp-backend-panel/litorbTest/iltorb/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/6.2.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/6.2.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/tararaapp-backend-panel/litorbTest/iltorb',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/tararaapp-backend-panel/litorbTest/iltorb/build'
  CC(target) Release/obj.target/decode/brotli/common/dictionary.o
  CC(target) Release/obj.target/decode/brotli/dec/bit_reader.o
  CC(target) Release/obj.target/decode/brotli/dec/decode.o
  CC(target) Release/obj.target/decode/brotli/dec/huffman.o
  CC(target) Release/obj.target/decode/brotli/dec/state.o
  CXX(target) Release/obj.target/decode/src/common/allocator.o
In file included from ../src/common/allocator.cc:2:
../../../node_modules/nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from /root/.node-gyp/6.2.0/include/node/node.h:42,
                 from ../../../node_modules/nan/nan.h:47,
                 from ../src/common/allocator.cc:2:
/root/.node-gyp/6.2.0/include/node/v8.h:341: error: expected unqualified-id before ‘using’
/root/.node-gyp/6.2.0/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/root/.node-gyp/6.2.0/include/node/v8.h:358: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.2.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/root/.node-gyp/6.2.0/include/node/v8.h:365: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.2.0/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/root/.node-gyp/6.2.0/include/node/v8.h:369: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.2.0/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/root/.node-gyp/6.2.0/include/node/v8.h:437: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.2.0/include/node/v8.h: At global scope:
/root/.node-gyp/6.2.0/include/node/v8.h:477: error: expected unqualified-id before ‘using’
/root/.node-gyp/6.2.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/root/.node-gyp/6.2.0/include/node/v8.h:809: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.2.0/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/root/.node-gyp/6.2.0/include/node/v8.h:834: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.2.0/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/root/.node-gyp/6.2.0/include/node/v8.h:846: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.2.0/include/node/v8.h: At global scope:
/root/.node-gyp/6.2.0/include/node/v8.h:871: error: expected unqualified-id before ‘using’
/root/.node-gyp/6.2.0/include/node/v8.h:1108: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.2.0/include/node/v8.h:1114: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.2.0/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Cont
ext>) const’:
/root/.node-gyp/6.2.0/include/node/v8.h:3246: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.2.0/include/node/v8.h: At global scope:
/root/.node-gyp/6.2.0/include/node/v8.h:4463: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.2.0/include/node/v8.h:4479: error: ‘nullptr’ was not declared in this scope
/root/.node-gyp/6.2.0/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/root/.node-gyp/6.2.0/include/node/v8.h:7348: error: ‘nullptr’ was not declared in this scope
In file included from ../../../node_modules/nan/nan.h:190,
                 from ../src/common/allocator.cc:2:
../../../node_modules/nan/nan_maybe_43_inl.h: At global scope:
../../../node_modules/nan/nan_maybe_43_inl.h:13: error: expected unqualified-id before ‘using’
../../../node_modules/nan/nan_maybe_43_inl.h:16: error: expected unqualified-id before ‘using’
../../../node_modules/nan/nan_maybe_43_inl.h:19: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:24: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:31: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:36: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:41: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:46: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:51: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:59: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:64: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:69: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:76: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:83: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:91: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:98: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:108: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:114: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:118: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:125: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:130: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:135: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:139: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:145: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:150: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:156: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:162: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:168: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:174: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:180: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:186: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:194: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:201: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:205: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:209: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:213: error: expected initializer before ‘<’ token
../../../node_modules/nan/nan_maybe_43_inl.h:217: error: expected initializer before ‘<’ token
../src/common/allocator.cc:48: error: expected ‘}’ at end of input
../../../node_modules/nan/nan_callbacks_12_inl.h:167: warning: ‘void Nan::imp::FunctionCallbackWrapper(const v8::FunctionCallbackInf
o<v8::Value>&)’ defined but not used
../../../node_modules/nan/nan_callbacks_12_inl.h:181: warning: ‘void Nan::imp::GetterCallbackWrapper(v8::Local<v8::Name>, const v8::
PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../../node_modules/nan/nan_callbacks_12_inl.h:197: warning: ‘void Nan::imp::SetterCallbackWrapper(v8::Local<v8::Name>, v8::Local<
v8::Value>, const v8::PropertyCallbackInfo<void>&)’ defined but not used
../../../node_modules/nan/nan_callbacks_12_inl.h:253: warning: ‘void Nan::imp::PropertyGetterCallbackWrapper(v8::Local<v8::Name>, co
nst v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../../node_modules/nan/nan_callbacks_12_inl.h:270: warning: ‘void Nan::imp::PropertySetterCallbackWrapper(v8::Local<v8::Name>, v8
::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../../node_modules/nan/nan_callbacks_12_inl.h:290: warning: ‘void Nan::imp::PropertyEnumeratorCallbackWrapper(const v8::PropertyC
allbackInfo<v8::Array>&)’ defined but not used
../../../node_modules/nan/nan_callbacks_12_inl.h:306: warning: ‘void Nan::imp::PropertyDeleterCallbackWrapper(v8::Local<v8::Name>, c
onst v8::PropertyCallbackInfo<v8::Boolean>&)’ defined but not used
../../../node_modules/nan/nan_callbacks_12_inl.h:323: warning: ‘void Nan::imp::PropertyQueryCallbackWrapper(v8::Local<v8::Name>, con
st v8::PropertyCallbackInfo<v8::Integer>&)’ defined but not used
../../../node_modules/nan/nan_callbacks_12_inl.h:428: warning: ‘void Nan::imp::IndexGetterCallbackWrapper(uint32_t, const v8::Proper
tyCallbackInfo<v8::Value>&)’ defined but not used
../../../node_modules/nan/nan_callbacks_12_inl.h:444: warning: ‘void Nan::imp::IndexSetterCallbackWrapper(uint32_t, v8::Local<v8::Va
lue>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not used
../../../node_modules/nan/nan_callbacks_12_inl.h:464: warning: ‘void Nan::imp::IndexEnumeratorCallbackWrapper(const v8::PropertyCall
backInfo<v8::Array>&)’ defined but not used
../../../node_modules/nan/nan_callbacks_12_inl.h:480: warning: ‘void Nan::imp::IndexDeleterCallbackWrapper(uint32_t, const v8::Prope
rtyCallbackInfo<v8::Boolean>&)’ defined but not used
../../../node_modules/nan/nan_callbacks_12_inl.h:496: warning: ‘void Nan::imp::IndexQueryCallbackWrapper(uint32_t, const v8::Propert
yCallbackInfo<v8::Integer>&)’ defined but not used
make: *** [Release/obj.target/decode/src/common/allocator.o] Error 1
make: Leaving directory `/home/tararaapp-backend-panel/litorbTest/iltorb/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 2.6.32-642.1.1.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/tararaapp-backend-panel/litorbTest/iltorb
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
root@server [/home/tararaapp-backend-panel/litorbTest/iltorb]# 
```

Thanks for replying so quickly.

**Comment by MayhemYDG** [comment]
`../../../node_modules/nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler`
Big clue right there. You need an updated gcc/g++, probably [version 4.8](https://github.com/MayhemYDG/iltorb/blob/master/.travis.yml#L18).

**Comment by mokingguy** [comment]
You're absolutely right, that was it, You're awesome thank you so much

**Comment by demircancelebi** [comment]
I also get a similar error, maybe someone here can also help me with that

```
> iltorb@1.0.12 install /Users/demir/Desktop/www/other/new-project/node_modules/iltorb
> node-gyp rebuild

  CC(target) Release/obj.target/decode/brotli/common/dictionary.o
./Release/.deps/Release/obj.target/decode/brotli/common/dictionary.o.d.raw { dev: 16777220,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 63886237,
  size: 151,
  blocks: 8,
  atime: 2016-09-01T23:49:24.000Z,
  mtime: 2016-09-01T23:49:24.000Z,
  ctime: 2016-09-01T23:49:24.000Z,
  birthtime: 2016-09-01T23:49:24.000Z }
  CC(target) Release/obj.target/decode/brotli/dec/bit_reader.o
./Release/.deps/Release/obj.target/decode/brotli/dec/bit_reader.o.d.raw { dev: 16777220,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 63886242,
  size: 205,
  blocks: 8,
  atime: 2016-09-01T23:49:24.000Z,
  mtime: 2016-09-01T23:49:24.000Z,
  ctime: 2016-09-01T23:49:24.000Z,
  birthtime: 2016-09-01T23:49:24.000Z }
  CC(target) Release/obj.target/decode/brotli/dec/decode.o
./Release/.deps/Release/obj.target/decode/brotli/dec/decode.o.d.raw { dev: 16777220,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 63886246,
  size: 440,
  blocks: 8,
  atime: 2016-09-01T23:49:25.000Z,
  mtime: 2016-09-01T23:49:25.000Z,
  ctime: 2016-09-01T23:49:25.000Z,
  birthtime: 2016-09-01T23:49:25.000Z }
  CC(target) Release/obj.target/decode/brotli/dec/huffman.o
./Release/.deps/Release/obj.target/decode/brotli/dec/huffman.o.d.raw { dev: 16777220,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 63886249,
  size: 232,
  blocks: 8,
  atime: 2016-09-01T23:49:25.000Z,
  mtime: 2016-09-01T23:49:25.000Z,
  ctime: 2016-09-01T23:49:25.000Z,
  birthtime: 2016-09-01T23:49:25.000Z }
  CC(target) Release/obj.target/decode/brotli/dec/state.o
./Release/.deps/Release/obj.target/decode/brotli/dec/state.o.d.raw { dev: 16777220,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 63886252,
  size: 285,
  blocks: 8,
  atime: 2016-09-01T23:49:26.000Z,
  mtime: 2016-09-01T23:49:26.000Z,
  ctime: 2016-09-01T23:49:26.000Z,
  birthtime: 2016-09-01T23:49:26.000Z }
  CXX(target) Release/obj.target/decode/src/common/allocator.o
In file included from ../src/common/allocator.cc:2:
../../nan/nan.h:23:10: fatal error: 'node_version.h' file not found
#include <node_version.h>
         ^
1 error generated.
make: *** [Release/obj.target/decode/src/common/allocator.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/demir/Desktop/www/other/new-project/node_modules/iltorb
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
new-project@0.0.0 /Users/demir/Desktop/www/other/new-project
└── (empty)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "shrink-ray"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! iltorb@1.0.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iltorb@1.0.12 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iltorb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iltorb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iltorb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/demir/Desktop/www/other/new-project/npm-debug.log
npm ERR! code 1
```

**Comment by MayhemYDG** [comment]
@demircancelebi you shouldn't need to install gcc or alias anything on macOS, the Xcode Command Line Tools should be enough.

**Comment by mokingguy** [comment]
@MayhemYDG @demircancelebi  Yeah, My work mac works just fine, it was just an issue on my server. Did you installed the Xcode Command Line Tools? What version of OSX are you running?

**Comment by demircancelebi** [comment]
Hi @mokingguy, I use El Capitan, `10.11.6 (15G31)` to be exact. I installed `Command Line Tools (OS X 10.11) for Xcode 7.3.1` (though it was already installed), and I still see this when I run `npm i iltorb`

```
> iltorb@1.0.12 install /Users/demir/Desktop/www/other/new-project/node_modules/iltorb
> node-gyp rebuild

  CC(target) Release/obj.target/decode/brotli/common/dictionary.o
  CC(target) Release/obj.target/decode/brotli/dec/bit_reader.o
  CC(target) Release/obj.target/decode/brotli/dec/decode.o
  CC(target) Release/obj.target/decode/brotli/dec/huffman.o
  CC(target) Release/obj.target/decode/brotli/dec/state.o
  CXX(target) Release/obj.target/decode/src/common/allocator.o
In file included from ../src/common/allocator.cc:2:
../../nan/nan.h:23:10: fatal error: 'node_version.h' file not found
#include <node_version.h>
         ^
1 error generated.
make: *** [Release/obj.target/decode/src/common/allocator.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/demir/Desktop/www/other/new-project/node_modules/iltorb
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/Users/demir/Desktop/www/other/new-project/package.json'
npm WARN new-project No description
npm WARN new-project No repository field.
npm WARN new-project No README data
npm WARN new-project No license field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "iltorb"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! iltorb@1.0.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iltorb@1.0.12 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iltorb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iltorb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iltorb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/demir/Desktop/www/other/new-project/npm-debug.log
```

**Comment by MayhemYDG** [comment]
```
../../nan/nan.h:23:10: fatal error: 'node_version.h' file not found
```
Could be a faulty node install? Try updating node and npm.
