### ISSUE TITLE
"/tmp/cctsPkyM.s:131: Error: expecting string instruction after `rep'" When doing node-gyp rebuild

### ISSUE THREAD

**Issue by mokingguy** [MayhemYDG/iltorb#19]
Hi, its me again :/

I get an error on npm install on a new project and i did the same steps that we did in [here](https://github.com/MayhemYDG/iltorb/issues/14)

the node-gyp rebuild says 

````
gyp info it worked if it ends with ok                                                                                                                       
gyp info using node-gyp@3.4.0                                                                                                                               
gyp info using node@6.2.0 | linux | x64                                                                                                                     
gyp info spawn /usr/bin/python2                                                                                                                             
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',                                                                               
gyp info spawn args   'binding.gyp',                                                                                                                        
gyp info spawn args   '-f',                                                                                                                                 
gyp info spawn args   'make',                                                                                                                               
gyp info spawn args   '-I',                                                                                                                                 
gyp info spawn args   '/home/tararaapp-backend-panel/litorbTest/iltorb/build/config.gypi',                                                                  
gyp info spawn args   '-I',                                                                                                                                 
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',                                                                                    
gyp info spawn args   '-I',                                                                                                                                 
gyp info spawn args   '/root/.node-gyp/6.2.0/include/node/common.gypi',                                                                                     
gyp info spawn args   '-Dlibrary=shared_library',                                                                                                           
gyp info spawn args   '-Dvisibility=default',                                                                                                               
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/6.2.0',                                                                                              
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',                                                                                
gyp info spawn args   '-Dnode_lib_file=node.lib',                                                                                                           
gyp info spawn args   '-Dmodule_root_dir=/home/tararaapp-backend-panel/litorbTest/iltorb',                                                                  
gyp info spawn args   '--depth=.',                                                                                                                          
gyp info spawn args   '--no-parallel',                                                                                                                      
gyp info spawn args   '--generator-output',                                                                                                                 
gyp info spawn args   'build',                                                                                                                              
gyp info spawn args   '-Goutput_dir=.' ]                                                                                                                    
gyp info spawn make                                                                                                                                         
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]                                                                                                  
make: Entering directory `/home/tararaapp-backend-panel/litorbTest/iltorb/build'                                                                            
  CC(target) Release/obj.target/decode/brotli/common/dictionary.o                                                                                           
  CC(target) Release/obj.target/decode/brotli/dec/bit_reader.o                                                                                              
  CC(target) Release/obj.target/decode/brotli/dec/decode.o                                                                                                  
  CC(target) Release/obj.target/decode/brotli/dec/huffman.o                                                                                                 
  CC(target) Release/obj.target/decode/brotli/dec/state.o                                                                                                   
  CXX(target) Release/obj.target/decode/src/common/allocator.o                                                                                              
/tmp/cctsPkyM.s: Assembler messages:                                                                                                                        
/tmp/cctsPkyM.s:131: Error: expecting string instruction after `rep'                                                                                        
make: *** [Release/obj.target/decode/src/common/allocator.o] Error 1                                                                                        
make: Leaving directory `/home/tararaapp-backend-panel/litorbTest/iltorb/build'                                                                             
gyp ERR! build error                                                                                                                                        
gyp ERR! stack Error: `make` failed with exit code: 2                                                                                                       
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 2.6.32-642.6.199.2.cpanel6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/tararaapp-backend-panel/litorbTest/iltorb
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
````

I checked and im running gcc 4.8 that was the issue last time.
Any idea?

**Comment by addaleax** [comment]
Can you run `export CFLAGS=-save-temps` before running node-gyp rebuild? That should leave the problematic `.s` file in the `build/` directory so that one can look at it

**Comment by mokingguy** [comment]
Like this?

```
root@server [/home/tararaapp-backend-panel/litorbTest/iltorb]# export CFLAGS=-save-temps                                                                    
root@server [/home/tararaapp-backend-panel/litorbTest/iltorb]# node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.2.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/tararaapp-backend-panel/litorbTest/iltorb/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/6.2.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/6.2.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/tararaapp-backend-panel/litorbTest/iltorb',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/tararaapp-backend-panel/litorbTest/iltorb/build'
  CC(target) Release/obj.target/decode/brotli/common/dictionary.o
  CC(target) Release/obj.target/decode/brotli/dec/bit_reader.o
  CC(target) Release/obj.target/decode/brotli/dec/decode.o
  CC(target) Release/obj.target/decode/brotli/dec/huffman.o
  CC(target) Release/obj.target/decode/brotli/dec/state.o
  CXX(target) Release/obj.target/decode/src/common/allocator.o
/tmp/cckIXZ8J.s: Assembler messages:
/tmp/cckIXZ8J.s:131: Error: expecting string instruction after `rep'
make: *** [Release/obj.target/decode/src/common/allocator.o] Error 1
make: Leaving directory `/home/tararaapp-backend-panel/litorbTest/iltorb/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 2.6.32-642.6.199.2.cpanel6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/tararaapp-backend-panel/litorbTest/iltorb
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

**Comment by addaleax** [comment]
hm, not sure that worked – does the `/tmp/cckIXZ8J.s` still exist after trying to build? would you be willing to share it?

**Comment by mokingguy** [comment]
That file does not exist...

**Comment by addaleax** [comment]
Are there `.s` files in `build/`? That’s where they end up on my machine…

(Generally, yeah, this looks like a compiler bug. Which versions are you using?)

**Comment by mokingguy** [comment]
In build/ i have 

- bit_reader.s
- dictionary.s
- decode.s
- huffman.s
- state.s

It has
gcc 4.8
node  6.2.0
npm 4.0.2
node-gyp 3.4.0
make 3.81
python 2.6

**Comment by addaleax** [comment]
Eek. Well, it’s a bit more verbose, but this should work: You can run node-gyp as `node-gyp --verbose rebuild`, which should include something like near the end:
```
  g++ '-DNODE_GYP_MODULE_NAME=decode' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/home/xxxx/src/node/include/node -I/home/xxxx/src/node/src -I/home/xxxx/src/node/deps/uv/include -I/home/xxxx/src/node/deps/v8/include -I../node_modules/nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O2 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF ./Release/.deps/Release/obj.target/decode/src/common/allocator.o.d.raw   -c -o Release/obj.target/decode/src/common/allocator.o ../src/common/allocator.cc
../src/common/allocator.cc: Assembler messages:
../src/common/allocator.cc:9: Error: no such instruction: `repx'
```

When you `cd` into `build`, run that g++ command you are seeing and make sure that it still fails (everything from g++ to ../src/common/allocator.cc). It should produce the same error.

Then, run it again, but replace `-c -o Release/obj.target/decode/src/common/allocator.o ../src/common/allocator.cc` at the end with `-S -o /tmp/allocator.s ../src/common/allocator.cc`. That should not fail and produce /tmp/allocator.s as the output, which should contain a bit of helpful information

**Comment by mokingguy** [comment]
I think that worked, here's the file, i don't understand what that means but maybe you can make sense of it.

[allocator.s.zip](https://github.com/MayhemYDG/iltorb/files/600813/allocator.s.zip)

**Comment by addaleax** [comment]
Looks like you’re running into the problem described @ https://gcc.gnu.org/bugzilla/show_bug.cgi?id=57017, maybe that’s helpful? (Also: This [warning inside scons](https://gitlab-beta.engr.illinois.edu/ejclark2/gem5i/commit/aa2a2693485735dec25c8e4d5f0edd79c5485ad3) contains information on *why* this fails/which compiler versions it fails with)

**Comment by mokingguy** [comment]
Ok, from what i gather there is that is a compiler issue, I've updated centos devtoolset from 2 to 4, but that did nothing. the same error, I don't know what to do. Is there an easy way to fix this?

**Comment by mokingguy** [comment]
Ok, bizarre moment, I rebuilt iltorb with devtoolset-4 an got an missing module error

````
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:409:26)
    at node.js:579:27
    at nextTickCallbackWith0Args (node.js:420:9)
````

I did `npm install` en rebuild again, and it worked.
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@4.4.5 | linux | x64
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/centrohistorico/iltorb/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/4.4.5/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/4.4.5',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/centrohistorico/iltorb',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/centrohistorico/iltorb/build'
  CC(target) Release/obj.target/decode/brotli/common/dictionary.o
  CC(target) Release/obj.target/decode/brotli/dec/bit_reader.o
  CC(target) Release/obj.target/decode/brotli/dec/decode.o
  CC(target) Release/obj.target/decode/brotli/dec/huffman.o
  CC(target) Release/obj.target/decode/brotli/dec/state.o
  CXX(target) Release/obj.target/decode/src/common/allocator.o
  CXX(target) Release/obj.target/decode/src/common/stream_coder.o
  CXX(target) Release/obj.target/decode/src/dec/decode_index.o
  CXX(target) Release/obj.target/decode/src/dec/stream_decode.o
  CXX(target) Release/obj.target/decode/src/dec/stream_decode_worker.o
  SOLINK_MODULE(target) Release/obj.target/decode.node
  COPY Release/decode.node
  CC(target) Release/obj.target/encode/brotli/common/dictionary.o
  CC(target) Release/obj.target/encode/brotli/enc/backward_references.o
  CC(target) Release/obj.target/encode/brotli/enc/bit_cost.o
  CC(target) Release/obj.target/encode/brotli/enc/block_splitter.o
  CC(target) Release/obj.target/encode/brotli/enc/brotli_bit_stream.o
  CC(target) Release/obj.target/encode/brotli/enc/cluster.o
  CC(target) Release/obj.target/encode/brotli/enc/compress_fragment.o
  CC(target) Release/obj.target/encode/brotli/enc/compress_fragment_two_pass.o
  CC(target) Release/obj.target/encode/brotli/enc/encode.o
  CC(target) Release/obj.target/encode/brotli/enc/entropy_encode.o
  CC(target) Release/obj.target/encode/brotli/enc/histogram.o
  CC(target) Release/obj.target/encode/brotli/enc/literal_cost.o
  CC(target) Release/obj.target/encode/brotli/enc/memory.o
  CC(target) Release/obj.target/encode/brotli/enc/metablock.o
  CC(target) Release/obj.target/encode/brotli/enc/static_dict.o
  CC(target) Release/obj.target/encode/brotli/enc/utf8_util.o
  CXX(target) Release/obj.target/encode/src/common/allocator.o
  CXX(target) Release/obj.target/encode/src/common/stream_coder.o
  CXX(target) Release/obj.target/encode/src/enc/encode_index.o
  CXX(target) Release/obj.target/encode/src/enc/stream_encode.o
  CXX(target) Release/obj.target/encode/src/enc/stream_encode_worker.o
  SOLINK_MODULE(target) Release/obj.target/encode.node
  COPY Release/encode.node
make: Leaving directory `/home/centrohistorico/iltorb/build'
gyp info ok 
```
 but the npm install keeps failing, the npm error is

```
root@server [/home/centrohistorico/centrohistorico-webpanel]# npm install shrink-ray                                                                                     
                                                                                                                                                                         
> iltorb@1.0.13 install /home/centrohistorico/centrohistorico-webpanel/node_modules/iltorb
> node-gyp rebuild

gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: spawn EACCES
gyp ERR! stack     at exports._errnoException (util.js:870:11)
gyp ERR! stack     at ChildProcess.spawn (internal/child_process.js:298:11)
gyp ERR! stack     at exports.spawn (child_process.js:362:9)
gyp ERR! stack     at exports.execFile (child_process.js:151:15)
gyp ERR! stack     at checkPythonVersion (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:419:5)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:361:9
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:88:20
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 2.6.32-642.6.2.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/centrohistorico/centrohistorico-webpanel/node_modules/iltorb
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
centrohistorico@0.0.0 /home/centrohistorico/centrohistorico-webpanel                                                                                                     
└── (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/stylint/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 2.6.32-642.6.2.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "shrink-ray"
npm ERR! node v4.4.5
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE

npm ERR! iltorb@1.0.13 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the iltorb@1.0.13 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iltorb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iltorb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iltorb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/centrohistorico/centrohistorico-webpanel/npm-debug.log
```

**Comment by addaleax** [comment]
That is likely a different error now, and one that iltorb can’t do much about. I would suggest trying to run `python -c 'import platform; print(platform.python_version());'` manually and see if that works?

**Comment by MayhemYDG** [comment]
Closing this as this doesn't appear to be an issue with iltorb itself.

**Comment by mokingguy** [comment]
Almost 4 months later I finally solved it, it was a combination of having to use [devtoolset-4](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-4/) on CentOS and a bug within NPM itself that failed to build iltorb when the user is root. 

Commenting here if some poor soul has the same problem as me, and thank you guys for at least pointing me at the right direction

**Comment by MayhemYDG** [comment]
You don't want to install npm packages as root, really.
