### ISSUE TITLE
SyntaxError: Unexpected token ,

### ISSUE THREAD

**Issue by nickdesaulniers** [MayhemYDG/iltorb#2]
```
➜  brotli  node app.js
/Users/Nicholas/code/js/brotli/node_modules/iltorb/index.js:98
    blockSize,
             ^
SyntaxError: Unexpected token ,
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Nicholas/code/js/brotli/app.js:4:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```
https://github.com/MayhemYDG/iltorb/blob/master/index.js#L99

**Comment by MayhemYDG** [comment]
Closing this as it's essentially the same as #1: lack of support for older Node.js.
