### ISSUE TITLE
Error: Module version mismatch. Expected 46, got 57.

### ISSUE THREAD

**Issue by rollermy** [MayhemYDG/iltorb#36]
I'm getting this error trying to serve my app on npm 5.03 and both node 6.0.0 and 8.1.2 
Seems like it is coming for iltorb, i'm on version 1.3.1
Thanks for help getting my app going again. All i can tell is that it is looking for version 46 of something and is getting newer.

Error: Module version mismatch. Expected 46, got 57.
     at Error (native)
     at Object.Module._extensions..node (module.js:434:18)
     at Module.load (module.js:343:32)
     at Function.Module._load (module.js:300:12)
     at Module.require (module.js:353:17)
     at require (internal/module.js:12:17)
     at Object.<anonymous> (/home/user/site/node_modules/iltorb/index.js:10:16)
     at Module._compile (module.js:409:26)
     at Object.Module._extensions..js (module.js:416:10)
     at Module.load (module.js:343:32)
     at Function.Module._load (module.js:300:12)
     at Module.require (module.js:353:17)
     at require (internal/module.js:12:17)
     at Object.<anonymous> (/home/user/site/node_modules/shrink-ray/index.js:22:14)
     at Module._compile (module.js:409:26)
     at Object.Module._extensions..js (module.js:416:10)
     at Module.load (module.js:343:32)
     at Function.Module._load (module.js:300:12)
     at Module.require (module.js:353:17)
     at require (internal/module.js:12:17)
     at Object.<anonymous> (/home/user/site/live/server/config/express.js:131:18)
     at Module._compile (module.js:409:26)

**Comment by MayhemYDG** [comment]
Sounds like the compiled binaries don't match your Node version. Try deleting your node_modules then re-installing your dependencies again.

**Comment by rollermy** [comment]
Thanks. I tried that several times without success. 
I downgraded to node 4.6 and reinstalled the node modules. That let it work.

**Comment by MayhemYDG** [comment]
It should work just fine on more recent versions of Node as well. 🤔

**Comment by oohnoitz** [comment]
Not entirely sure how this would happen with the info you provided. Using the [releases](https://nodejs.org/en/download/releases/) page as a reference...
- the ABI for Node 4.x is `46`
- the ABI for Node 6.x is `48` which doesn't seem related to your issue at all
- the compiled version you were trying to run was for Node 8.x which targets ABI `57`

I'm wondering if this is an environmental issue where you somehow are installing the dependencies with Node 8.x but still somehow starting up your app with Node 4.x instead. This might be due to your deployment configured or how you have Node installed on the server.

**Comment by rollermy** [comment]
Thanks guys. I'll have to reinstall node to see if that helps

**Comment by MayhemYDG** [comment]
@rollermy Is  your issue resolved then?

**Comment by rollermy** [comment]
@MayhemYDG Just tried it. It was using the wrong version of node.
Thanks for your help!
