### ISSUE TITLE
npm install script fails

### ISSUE THREAD

**Issue by ehmicky** [MayhemYDG/iltorb#68]
`prebuild-install` dependency has just been updated to `3.0.0`.

However [`downloadPrebuild()`](https://github.com/prebuild/prebuild-install/blob/master/download.js) now signature is now different and does not match the [install script](https://github.com/MayhemYDG/iltorb/blob/master/scripts/install.js) causing this error message on installation:
```
> iltorb@2.3.1 install .../node_modules/iltorb
> node ./scripts/install.js || node-gyp rebuild

.../node_modules/prebuild-install/util.js:71
  return path.join(prebuildCache(), url.replace(/[^a-zA-Z0-9.]+/g, '-'))
                                        ^

TypeError: url.replace is not a function
    at Object.cachedPrebuild (.../node_modules/prebuild-install/util.js:71:41)
    at downloadPrebuild (.../node_modules/prebuild-install/download.js:17:29)
    at Object.<anonymous> (.../node_modules/iltorb/scripts/install.js:47:1)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
```

**Comment by MayhemYDG** [comment]
@ehmicky 
Can you try to install the master branch to see if it's properly fixed on your end as well?
```
npm i MayhemYDG/iltorb
```

**Comment by ehmicky** [comment]
Yes it is, thanks!
