### ISSUE TITLE
Worker Threads: "Module did not self-register"

### ISSUE THREAD

**Issue by mattolson** [MayhemYDG/iltorb#78]
When using the new experimental worker threads in Node 10.5 and above, if you require `iltorb` in both the parent and the worker, the following error is thrown:

```
Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/matt.olson/workspace/storefront-renderer/node_modules/iltorb/index.js:10:40)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

This seems to be related to nodejs/node#21783 and nodejs/node#21481. I believe the issue is that the [module needs to be context-aware](https://nodejs.org/api/addons.html#addons_context_aware_addons).

I ran into a similar [issue with the lzo package](https://github.com/schroffl/node-lzo/issues/10) and have a [PR](https://github.com/schroffl/node-lzo/pull/11) open for it. We will need to do something similar here.

**Comment by MayhemYDG** [comment]
@mattolson Thanks for reporting this issue! Could you double-check if the fix on master works for you?

**Comment by MayhemYDG** [comment]
It looks like `NAPI_MODULE_INIT` is not available for Node 6 and 8, I wonder if it'll get backported.

**Comment by mattolson** [comment]
@MayhemYDG Thanks!

**Comment by mattolson** [comment]
This is working for me, can you create a new release?

**Comment by MayhemYDG** [comment]
I've been waiting for [AppVeyor to suport Node 11](https://github.com/appveyor/ci/issues/2707), but I guess we'll have to do without it. I'll do a release in the evening.

**Comment by MayhemYDG** [comment]
@mattolson 2.4.1 is now published
