### ISSUE TITLE
electron build fails

### ISSUE THREAD

**Issue by Teranode** [MayhemYDG/iltorb#84]
Im getting this error when it tries to build with electron.
Do I manually compile it and if so how do i link it to the electron project
```
Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:
$ node ./scripts/install.js || node-gyp rebuild

C:\Users\kuris\OneDrive\Documents\animefever\node_modules\iltorb>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  dictionary.c
  transform.c
  bit_reader.c
  decode.c
  huffman.c
  state.c
  backward_references.c
  backward_references_hq.c
  bit_cost.c
  block_splitter.c
  brotli_bit_stream.c
  cluster.c
  compress_fragment.c
  compress_fragment_two_pass.c
  dictionary_hash.c
  encode.c
  encoder_dict.c
  entropy_encode.c
  histogram.c
  literal_cost.c
  memory.c
  metablock.c
  static_dict.c
  utf8_util.c
  allocator.cc
  stream_coder.cc
  stream_decode.cc
  stream_decode_worker.cc
  stream_encode.cc
  stream_encode_worker.cc
  iltorb.cc
  win_delay_load_hook.cc
c:\users\kuris\onedrive\documents\animefever\node_modules\iltorb\src\common\allocator.cc(35): warning C4146: unary minus operator applied to unsigned type, result still unsigned [C:\Users\kuris\OneDrive\Documents\animefever\node_modules\iltorb\build\iltorb.vcxproj]
C:\Users\kuris\.electron-gyp\4.1.4\x64\node.lib : fatal error LNK1106: invalid file or disk full: cannot seek to 0x2014F8 [C:\Users\kuris\OneDrive\Documents\animefever\node_modules\iltorb\build\iltorb.vcxproj]
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Error output:
info looking for local prebuild @ prebuilds\iltorb-v2.3.2-electron-v69-win32-x64.tar.gz
info looking for cached prebuild @ C:\Users\kuris\AppData\Roaming\npm-cache\_prebuilds\https-github.com-MayhemYDG-iltorb-releases-download-v2.3.2-iltorb-v2.3.2-electron-v69-win32-x64.tar.gz
http request GET https://github.com/MayhemYDG/iltorb/releases/download/v2.3.2/iltorb-v2.3.2-electron-v69-win32-x64.tar.gz
http 404 https://github.com/MayhemYDG/iltorb/releases/download/v2.3.2/iltorb-v2.3.2-electron-v69-win32-x64.tar.gz
WARN install No prebuilt binaries found (target=4.1.4 runtime=electron arch=x64 platform=win32)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.10.0 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\kuris\\OneDrive\\Documents\\animefever\\node_modules\\iltorb\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\kuris\\.electron-gyp\\4.1.4\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\kuris\\.electron-gyp\\4.1.4',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\kuris\\.electron-gyp\\4.1.4\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\kuris\\OneDrive\\Documents\\animefever\\node_modules\\iltorb',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\kuris\\OneDrive\\Documents\\animefever\\node_modules\\iltorb\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\kuris\OneDrive\Documents\animefever\node_modules\iltorb
gyp ERR! node -v v11.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
error Command failed with exit code 1.

    at ChildProcess.childProcess.once.code (C:\Users\kuris\OneDrive\Documents\animefever\node_modules\builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:285:13)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
From previous event:
    at processImmediate (timers.js:637:19)
From previous event:
    at C:\Users\kuris\OneDrive\Documents\animefever\node_modules\app-builder-lib\src\util\yarn.ts:155:24
From previous event:
    at _rebuild (C:\Users\kuris\OneDrive\Documents\animefever\node_modules\app-builder-lib\src\util\yarn.ts:179:5)
    at rebuild (C:\Users\kuris\OneDrive\Documents\animefever\node_modules\app-builder-lib\out\util\yarn.js:163:19)
    at C:\Users\kuris\OneDrive\Documents\animefever\node_modules\app-builder-lib\src\util\yarn.ts:20:11
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:637:19)
From previous event:
    at _installOrRebuild (C:\Users\kuris\OneDrive\Documents\animefever\node_modules\app-builder-lib\out\util\yarn.js:71:28)
    at installOrRebuild (C:\Users\kuris\OneDrive\Documents\animefever\node_modules\app-builder-lib\out\util\yarn.js:55:28)
    at C:\Users\kuris\OneDrive\Documents\animefever\node_modules\app-builder-lib\src\packager.ts:509:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (C:\Users\kuris\OneDrive\Documents\animefever\node_modules\app-builder-lib\src\packager.ts:470:70)
    at C:\Users\kuris\OneDrive\Documents\animefever\node_modules\app-builder-lib\src\packager.ts:420:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (C:\Users\kuris\OneDrive\Documents\animefever\node_modules\app-builder-lib\src\packager.ts:396:24)
    at C:\Users\kuris\OneDrive\Documents\animefever\node_modules\app-builder-lib\src\packager.ts:366:57
    at Generator.next (<anonymous>)
    at C:\Users\kuris\OneDrive\Documents\animefever\node_modules\graceful-fs\graceful-fs.js:111:16
    at C:\Users\kuris\OneDrive\Documents\animefever\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqCallback.args [as oncomplete] (fs.js:145:20)
From previous event:
    at Packager._build (C:\Users\kuris\OneDrive\Documents\animefever\node_modules\app-builder-lib\src\packager.ts:335:133)
    at C:\Users\kuris\OneDrive\Documents\animefever\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:637:19)
From previous event:
    at Packager.build (C:\Users\kuris\OneDrive\Documents\animefever\node_modules\app-builder-lib\src\packager.ts:288:14)    at build (C:\Users\kuris\OneDrive\Documents\animefever\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (C:\Users\kuris\OneDrive\Documents\animefever\node_modules\electron-builder\src\builder.ts:228:10)
    at then (C:\Users\kuris\OneDrive\Documents\animefever\node_modules\electron-builder\src\cli\cli.ts:46:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by oohnoitz** [comment]
Please copy the error output, and put it in a code block or a gist next time instead. Anyway, it seems to be failing to compile properly in your environment. Can you try removing the `.electron-gyp` folder entirely and trying again?

**Comment by Teranode** [comment]
@oohnoitz i've updated the image to a code block
i think the issue is with gyp maybe?

**Comment by oohnoitz** [comment]
Yes, it's an issue with `node-gyp`. Did you try deleting the entire `C:\Users\kuris\.electron-gyp` folder before trying again?

**Comment by Teranode** [comment]
Thanks it's compiling now.
